### ISSUE TITLE
This page isn’t working - HTTP ERROR 500

### ISSUE THREAD

**Issue by twnku** [AmirMustafa/Twitter-API-Login-PHP#2]
i changed the consumer api key, secret and the callback url
but it shows 
`This page isn’t workingaft.twnxs.com is currently unable to handle this request.
HTTP ERROR 500`
but when i use the original its all fine, what happened

**Comment by AmirMustafa** [comment]
Hello,

You need to change the callback URL in your web application and twitter API dashboard. Once your API is confirmed from twitter end it will work.
